apiVersion: v2
name: reporting-init
description: A Helm chart for MOSIP Reporting Initialization.
type: application
version: 0.0.1-develop
appVersion: ""
maintainers:
  - email: info@mosip.io
    name: MOSIP
